version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:latest
    steps:
      - checkout
      - run:
          name: install
          command: |
            mkdir -p ./venv
            virtualenv ./venv
            . venv/bin/activate
            python xunit.py


